language: go

go:
  - "1.10.x"

sudo: required

services:
  - docker

script:
  - go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
