[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/ory/dockertest"
  version = "3.3.4"

[prune]
  go-tests = true
  unused-packages = true
